### ISSUE TITLE
About Ghost Events Last Article

### ISSUE THREAD

**Issue by Cola-Ace** [azsry/phasmophobia_mechanics#15]
in Ghost Events, you say "A ghost event will increase a random player's sanity by 20% (not sure if this is intended)", but in game, when the crosses successfully blocks a hunting, the player increases sanity by 20%, so it's not intentional.

**Comment by Mythra** [comment]
Hey I'm going through this repository, and cleaning house with the update. I agree this is probably not intentional, but I also think this guide probably shouldn't be making guesses on how the devs are thinking, and instead just present what the code actually does.

I'll be restructuring this repository anyway, but I'll be sure to remove this line.
